version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-proot" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin:latest
    # image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql

  app:
    build: .
    container_name: node_app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mobilefirst-backend
      PORT: 3000
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

volumes:
  db-data:
    driver: local
